# Generated by Django 5.1.3 on 2024-12-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Proyect',
        ),
    ]
